# Generated by Django 4.2.11 on 2025-05-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_booking_car_remove_booking_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
